version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dbcafe
      POSTGRES_USER: dbcafeuser
      POSTGRES_PASSWORD: dbcafepassword
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --chdir /app/backend --bind 0.0.0.0:8000 backend.wsgi:application
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://dbcafeuser:dbcafepassword@db:5432/dbcafe

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend