version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dbcafe
      POSTGRES_USER: dbcafeuser
      POSTGRES_PASSWORD: dbcafepassword
    ports:
      - "5433:5432"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://dbcafeuser:dbcafepassword@db:5432/dbcafe